# Generated by Django 5.0 on 2023-12-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0002_rename_tac_receipt_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
